.ifndef prefix
prefix=/usr
.endif

CXX = clang++
CXXFLAGS = -Wall -g -O3

all: main.cpp
	$(CXX) $(CXXFLAGS) -std=c++17 -o logfilegen utl.cpp params.cpp macro.cpp vars.cpp tpl.cpp pairfile.cpp logrot.cpp cycle.cpp main.cpp

clean:
	$(RM) logfilegen

uninstall:
	rm $(prefix)/bin/logfilegen

install: logfilegen
	install -m 0755 logfilegen $(prefix)/bin/logfilegen

#.PHONY: install
