ifndef prefix
prefix=/usr
endif

CXX = clang++
CXXFLAGS = -Wall -g -O3 -std=c++11

all: main.cpp
	$(CXX) $(CXXFLAGS) -std=c++11 -o logfilegen utl.cpp tpl.cpp pairfile.cpp logrot.cpp cycle.cpp main.cpp

clean:
	$(RM) logfilegen


uninstall:
	rm $(prefix)/bin/logfilegen

install: logfilegen
	install -m 0755 logfilegen $(prefix)/bin

.PHONY: install
