name: Docker


on:
  push:
    branches:    
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'TODO'
      - 'templates/**'
      - '.github/ISSUE_TEMPLATE/**'
    tags:
      - '*'
  workflow_dispatch:


env:
  PLATFORMS: linux/amd64,linux/arm64


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
            with:
                version: latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GitHub tag
        run: if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then echo "GITHUB_TAG=${GITHUB_REF_NAME}" >> "${GITHUB_ENV}"; else echo "GITHUB_TAG=${GITHUB_SHA::7}" >> "${GITHUB_ENV}"; fi

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.GITHUB_TAG }}
