name: MacARMBuild


on: workflow_dispatch


jobs:

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: make --makefile=Makefile.clang.macarm
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
       name: logfilegen-macos-arm64-binary
       path: logfilegen
