name: MacARMBuild


on: workflow_dispatch


jobs:

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: make --makefile=Makefile.clang.macarm
