# test
name: XBUILD-NEW

on: [workflow_dispatch]


jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prerequisites
     run: |
          sudo apt install prometheus-cpp-dev

    - name: Configure
      run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
    - name: "Build Project"
      run: cmake --build build --target all --config Release -- -j4

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: make

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: make
